add packaging for macos-arm64

diff --git a/.github/workflows/package_test_pypi.yml b/.github/workflows/package_test_pypi.yml
--- a/.github/workflows/package_test_pypi.yml
+++ b/.github/workflows/package_test_pypi.yml
@@ -7,21 +7,21 @@ on:
       - '*'  # Run on any new tag
   workflow_dispatch:  # Allow manual trigger
 
-jobs:
-  print-arch:
-    runs-on: ${{ matrix.os }}
-    strategy:
-      matrix:
-        os: [ubuntu-latest, macos-13, macos-latest]
-
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-
-      - name: Print architecture
-        run: uname -m
-
 # jobs:
+#   print-arch:
+#     runs-on: ${{ matrix.os }}
+#     strategy:
+#       matrix:
+#         os: [ubuntu-latest, macos-13, macos-latest]
+
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v3
+
+#       - name: Print architecture
+#         run: uname -m
+
+jobs:
   # build-package-linux:
   #   runs-on: ubuntu-latest
   #   steps:
@@ -149,5 +149,63 @@ jobs:
   #       with:
   #         name: ${{ env.ARTIFACT_NAME }}
   #         path: macos-build/squigualiser-*-macos-x86-64-binaries.tar.gz
+  build-package-macos-arm64:
+    runs-on: macos-latest
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          submodules: recursive
+      - name: make macos-build dir
+        run: |
+          mkdir -p macos-build && \
+          cp scripts/package_macos_arm64.sh macos-build/ && \
+          chmod +x macos-build/package_macos_arm64.sh
+      - name: run without docker
+        run: |
+          cd macos-build && \
+          ./package_macos_arm64.sh test_pypi && \
+          LATEST_TAG=$(git ls-remote --tags https://github.com/hiruna72/squigualiser.git | cut -d/ -f3 | grep -v '\^{}' | sort -V | tail -n1)
+          echo Latest tag: $LATEST_TAG && \
+          if [ -f squigualiser.tar.gz ]; then \
+            mv squigualiser.tar.gz squigualiser-$LATEST_TAG-macos-arm64-binaries.tar.gz; \
+          else \
+            echo 'squigualiser.tar.gz not found!'; \
+            exit 1; \
+          fi && \
+          cd ..
+      - name: decompress squigualiser tar.gz
+        run: |
+          if [ -f macos-build/squigualiser-*-macos-arm64-binaries.tar.gz ]; then
+            cp macos-build/squigualiser-*-macos-arm64-binaries.tar.gz .
+            echo "Decompressing squigualiser tar.gz"
+            tar -xzf squigualiser-*-macos-arm64-binaries.tar.gz
+          else
+            echo "No squigualiser tar.gz found!"
+            exit 1
+          fi
+      - name: quick run
+        run: |
+          ./squigualiser/squigualiser --help || exit 1
+      - name: Add squigualiser to PATH
+        run: echo "${{ github.workspace }}/squigualiser" >> $GITHUB_PATH
+      - name: test_reform
+        run: test/test_reform.sh
+      - name: test_realign
+        run: test/test_realign.sh
+      - name: test_signal_to_read_plot
+        run: test/test_plot_signal_to_read.sh --save_svg
+      - name: test_calculate_offsets
+        run: test/test_calculate_offsets.sh
+      - name: Get artifact filename
+        id: artifact_name
+        run: |
+          FILE=$(ls macos-build/squigualiser-*-macos-arm64-binaries.tar.gz)
+          BASENAME=$(basename "$FILE" .tar.gz)
+          echo "ARTIFACT_NAME=$BASENAME" >> $GITHUB_ENV
+      - name: Upload squigualiser tar.gz
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ env.ARTIFACT_NAME }}
+          path: macos-build/squigualiser-*-macos-arm64-binaries.tar.gz
 
 
